from __future__ import annotations

import importlib.util
import sys
import unittest
from pathlib import Path


HERE = Path(__file__).resolve().parent


def _load(name: str, filename: str):
    spec = importlib.util.spec_from_file_location(name, HERE / filename)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


BUILDER = _load("build_daihen_cockpit_for_acceptance", "build_daihen_cockpit.py")
ENHANCER = _load("enhance_daihen_cockpit_links_for_acceptance", "enhance_daihen_cockpit_links.py")


class DaihenCockpitMachineAcceptanceTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.model = BUILDER.load_model()
        cls.page = ENHANCER.enhance_page(BUILDER.page_content(cls.model), cls.model)

    def test_public_route_and_home_entry_contract(self):
        self.assertIn("permalink: /decision-cockpit/daihen/", self.page)
        # Home insertion is generated by build_daihen_cockpit.build(). Keep the
        # route literal stable so the entry point cannot silently drift.
        source = (HERE / "build_daihen_cockpit.py").read_text(encoding="utf-8")
        self.assertIn("/decision-cockpit/daihen/", source)
        self.assertIn("ダイヘン 投資判断コックピットを開く", source)

    def test_first_view_answers_why_change_and_hypothesis(self):
        first_view = self.page.split("## ⚠ 先に確認する注意点", 1)[0]
        self.assertIn("なぜ今日見る？", first_view)
        self.assertIn("前回から何が変わった？", first_view)
        self.assertIn("今の投資仮説は？", first_view)
        self.assertIn("FY2027 Q1決算後の利益ドライバーとForward PERを再確認する", first_view)
        self.assertIn("INTACT", first_view)

    def test_known_cta_resolves_and_unknown_routes_fail_closed(self):
        self.assertIn("/companies/infrastructure/6622-daihen/", self.page)
        self.assertIn("Forward PER専用ページはまだありません", self.page)
        self.assertIn("仮説専用ページはまだありません", self.page)
        self.assertIn("Decision History専用ページはまだありません", self.page)
        self.assertNotIn("/forward-per/6622", self.page)
        self.assertNotIn("/hypothesis/6622", self.page)
        self.assertNotIn("/decision-history/6622", self.page)

    def test_stale_price_is_explicit_not_silent_current(self):
        self.assertEqual(self.model["valuation"]["freshness"], "STALE")
        self.assertIn("情報が古いため再確認が必要", self.page)
        self.assertIn("PRICE_STALE_FOR_E2E", self.page)
        self.assertIn("株価情報が古い場合、現在の割安度として無警告では使用しません", self.page)

    def test_consensus_unavailable_is_not_zero_gap(self):
        self.assertEqual(self.model["expectations"]["status"], "UNAVAILABLE")
        self.assertIsNone(self.model["expectations"]["external_consensus_ref"])
        self.assertIn("現在取得できません", self.page)
        self.assertIn("Consensusを取得できない場合、gap=0や「差なし」とは表示しません", self.page)

    def test_portfolio_not_run_is_not_presented_as_safe(self):
        self.assertEqual(self.model["portfolio_preflight"]["status"], "NOT_RUN")
        self.assertIn("まだ確認を実行していません", self.page)
        self.assertIn("未設定ルールや未実行preflightから安全/危険を推測しません", self.page)

    def test_historical_and_current_refs_are_separate(self):
        history = self.model["decision_history"]
        self.assertNotEqual(history["historical_snapshot_ref"], history["comparison_ref"])
        self.assertIn(history["historical_snapshot_ref"], self.page)
        self.assertIn(history["comparison_ref"], self.page)
        self.assertIn("過去snapshotを現在のResearch / Valuationで書き換えません", self.page)

    def test_no_trade_recommendation_is_generated(self):
        self.assertIn("この画面は売買指示を生成しません", self.page)
        for forbidden in ("推奨: BUY", "推奨: SELL", "買い推奨", "売り推奨"):
            self.assertNotIn(forbidden, self.page)

    def test_owner_30_second_checklist_is_present(self):
        self.assertIn("## 30秒チェック", self.page)
        for phrase in (
            "なぜ今日ダイヘンを見るのか",
            "前回から何が変わったか",
            "Base EPSの主な根拠は何か",
            "Bear / Base / BullのForward PERはどうか",
            "市場期待データは利用可能か",
            "何が起きたら仮説が崩れるか",
            "次にどこを確認するか",
        ):
            self.assertIn(phrase, self.page)


if __name__ == "__main__":
    unittest.main()
